name: banksy-test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anndata=0.10.2
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.8.0
  - array-api-compat=1.4
  - arrow=1.3.0
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.1
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fonttools=4.43.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - glpk=5.0
  - gmp=6.2.1
  - h5py=3.10.0
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - igraph=0.10.7
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.4.0
  - jupyter_console=6.6.3
  - jupyter_core=5.4.0
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.7
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - leidenalg=0.10.1
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnsl=2.0.1
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvmlite=0.40.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.9.2
  - nbconvert-core=7.9.2
  - nbconvert-pandoc=7.9.2
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.1
  - notebook=7.0.5
  - notebook-shim=0.2.3
  - numba=0.57.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.3
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pynndescent=0.5.10
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-igraph=0.11.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qtconsole-base=5.4.4
  - qtpy=2.4.0
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scanpy=1.9.5
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - send2trash=1.8.2
  - session-info=1.0.0
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - stdlib-list=0.8.0
  - tbb=2021.10.0
  - terminado=0.17.1
  - texttable=1.7.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.11.2
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - umap-learn=0.5.4
  - uri-template=1.3.0
  - urllib3=2.0.6
  - wcwidth=0.2.8
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
